# code generated by ChatGPT to expedite importing games into my "games" table
# run using sample_games

task sample_games: :environment do
  require 'csv'

  CSV_FILE_PATH = Rails.root.join('db', 'seeds', 'board_games.csv')

  Game.destroy_all
  puts "Deleted existing games from 'games' table"
  
  puts "Importing board games from CSV..."

  CSV.foreach(CSV_FILE_PATH, headers: true) do |row|
    Game.create!(
      image: row['image'],
      title: row['title'],
      genre: row['genre'],
      complexity: row['complexity'],
      randomness: row['randomness'],
      min_players: row['min_players'],
      max_players: row['max_players'],
      duration: row['duration'],
      rating: row['rating'],
      website: row['website']
    )
  end

  puts "Board games import completed successfully!"
end
